### ISSUE TITLE
Theme Park (EU)

### ISSUE THREAD

**Issue by altiereslima** [libretro-mirrors/beetle-saturn-libretro#124]
all movies crash

![theme park 1995 electronic arts europe eu -180905-160305](https://user-images.githubusercontent.com/18044879/45115455-3e7c3080-b126-11e8-8358-5029f6b3b65c.png)
![theme park 1995 electronic arts europe eu -180905-160236](https://user-images.githubusercontent.com/18044879/45115456-3e7c3080-b126-11e8-91ae-a2e59212d6f4.png)

**Comment by hiddenasbestos** [comment]
Is this still a bug in v1.22.1 and is it a known good dump?

**Comment by altiereslima** [comment]
Same thing.
Rom from emupardise.

**Comment by hiddenasbestos** [comment]
Thanks. If you could try stand-alone mednafen that'd be really helpful. If it's a problem unique to this core then there's a chance it could be fixed but I'm not the emulator writer, just packaging it up for RetroArch, so there isn't much I can do if the problem is due to an error deep within the code.

**Comment by altiereslima** [comment]
Stand-alone Mednafen, crash.
