### ISSUE TITLE
Grandia freezes at the end of CD1

### ISSUE THREAD

**Issue by RaouleMenard** [libretro-mirrors/beetle-saturn-libretro#201]
Hello,

I've just completed Grandia CD1 using the excellent English fan translation, and when I should save before switching to CD2, the game freezes.

It seems this was fixed on Mednafen with what they call an "Horrible Hack".

Here's the changelog from version 1.22.2 to 1.23.0:
"SS: Fixed hang at end of disc 1 of "Grandia", with horrible per-game hack."

Any chances this could be ported to RetroArch?

Thanks!

**Comment by negativeExponent** [comment]
upload your savefile, as close as possible to where the need to swap disk is required. this should make it easier to test out and confirm rather than have to play the entire disk just to reach this point. A savestate would help as well, buts it no guarantee it will work.
i already looked at the bits and pieces required, just nid to confirm if this was all needed without having to resync the entire thing to latest upstream.

UPDATE:
Fix is on my repo, hopefully that should be enough for the game (UNTESTED): https://github.com/negativeExponent/beetle-saturn-libretro/tree/horrible_hacks

compile it and see if this helps

**Comment by RaouleMenard** [comment]
Hi and thanks for your help!
Here's my save files close to the end of CD1, plus a save states during the cutscene a few seconds before the freeze, attached. I'm using the Grandia English patch version 0.92.
[Grandia (Japan) (Disc 1).zip](https://github.com/libretro/beetle-saturn-libretro/files/6623760/Grandia.Japan.Disc.1.zip)
Unfortunately I don't have a setup to compile this. Can you please make a build? I will test it and report back.
Thanks again!

**Comment by negativeExponent** [comment]
thanks for the saves. this seemed to work.

(i'll attach image of disk 2 later, internet is busted)

i dont maintain this core though. youll have to ask some to fetch the changes from my repo, or sync this core with upstream

**Comment by negativeExponent** [comment]
![2021-06-09T21:28:39,966379397+08:00](https://user-images.githubusercontent.com/54053706/121366839-60a4dc00-c96c-11eb-9e30-b7bf36fe89d1.png)

well, heres the screenshot of the start of disk 2

**Comment by RaouleMenard** [comment]
This is awesome!

I'll ask to get this upstream, or worse case I'll have to build it myself - never done that before though.

Again, thanks a lot for your help!

**Comment by negativeExponent** [comment]
i think this can be closed now.
