### ISSUE TITLE
cant use gun with latest commit

### ISSUE THREAD

**Issue by ghost** [libretro-mirrors/beetle-saturn-libretro#94]
virtua gun not working anymore. crosshair/buttons not reacting to anything.

**Comment by inactive123** [comment]
@hiddenasbestos Can you respond to this? Hopefully the old lightgun behavior still works despite the new code we merged in RetroArch.

**Comment by hiddenasbestos** [comment]
Is this with latest front-end?

**Comment by hiddenasbestos** [comment]
The old apis should all still work, but the latest saturn commit relies on the new api only.

**Comment by ghost** [comment]
so this does not work will other available configurations then?

**Comment by hiddenasbestos** [comment]
I'm not sure what you mean by other configurations?

The lightgun support you've seen from me to date has been a hack, abusing other apis to make it work. This prompted development of a proper lightgun api that could be used for saturn/psx without hacky code. But as it's only been added today, any front end prior to that wont support it. The old lightgun api wasn't capable (due to lack of screen space position and offscreen flag)

**Comment by ghost** [comment]
what wrong with previous implementation if it still worked how its suppose
to with other drivers/OS?

**Comment by hiddenasbestos** [comment]
Lots of things with old api and existing retroarch implementation that I felt needed to be addressed so that it didn't "just work" but that it worked well.

Main problems were:
* Not enough buttons for future emulation of PS2.
* Required use of the pointer api for position - which front end isn't obliged to support and has a blind spot.
* No offscreen status flag.
* Lack of support for remapping mouse inputs in RetroArch forced that job onto the core.

Hope that answers why.

**Comment by andres-asm** [comment]
I'm a bit confused, right now I updated retroarch, beetle saturn and didn't map anything and it just worked.
What are the bindings for?

**Comment by ghost** [comment]
im not talking about the api(if it does support old implementation and does
not break other cores). im talking about the implementation, this
implementation for example. whats the use of having this peripheral if it
would not work with systems/OS/console/devices that supports the core.

cant even send PR since to at least have this alternate support/config atm
since you will just probably remove it like the one i did for assigning
right-lick for an already existing mdfn function to offscreen shot when we
have enough buttons to support on a typical mouse hardware.

**Comment by hiddenasbestos** [comment]
I think the problem might be a missing Linux or macOS driver for the new lightgun API in RetroArch which would result in the latest core not getting the lightgun data back it needs to function.

I can develop a fix for it but can't test it, so I noted dinput only as a caveat in the PR. Probably should have been louder about this outcome though, sorry.

**Comment by hiddenasbestos** [comment]
I've submitted an X11 driver update pull request to RetroArch. Should fix all the problems you're having on Linux. I'll get an automated compile result shortly but I'm not able to test if it works in practice.

Once it's working you should be able to remap the right-click like you had before but in a more flexible way that supports other input devices too. That's the theory anyway!

**Comment by andres-asm** [comment]
Ok so I updated the core and now there are no inputs unless I map my mouse in settings?
I guess that's the intention and it should be mostly a map once and forget affair.

I think it's a change for the best.

**Comment by andres-asm** [comment]
Any recommended lightguns? I'm curious now

**Comment by hiddenasbestos** [comment]
Hi @fr500 - I use a "dolphin bar" which you can sync wiimotes to. It has several modes of operation but mode 2 is the best for RetroArch right now as it emulates a mouse with A as left mouse and B as right mouse (plus a few keyboard inputs for buttons on the wiimote). I then plug the wiimote into a comically large plastic handgun shell ("Datel Precision FX Pistol") for increased immersion.

I use the new remapping to put trigger on mouse 2, reload on mouse 1 and start on enter (mapped to the wiimote plus button by the dolphin bar).

Other guns I'm aware of are the Aimtrak and EMS Top Gun 3 but I have no experience with either those and cost too much for me anyway (especially vs. having wiimotes that I can use for other things).

For a future update I'd like to support the dolphin bar properly in it's "mode 4" - which allows multiple wiimotes to be synced and that should let two player Virtua Cop to be played with a little more work on the core. Maybe I could get in touch with whoever is working on the Dolphin port to ask them about adding a wiimote driver to the front-end? Not sure I have the time to take on such a big job alone.

**Comment by andres-asm** [comment]
aliaspider is no longer contributing to libretro.
For dolphin, instead of getting a wiimote driver we were thinking about USB passthrough (integrating libusb in the core) to allow native wiimote support.

But nothing is currently on/off the cards.

**Comment by hiddenasbestos** [comment]
Well I should say that as far as I'm aware, the dolphin bar actually does some of the bluetooth side of things itself and presents as a USB input device rather than a BT dongle. Although I imagine there's quite a bit of cross-over with their BT stack since it supports rumble and the on-board speaker. I'm no expert on how this stuff works though, this is just from experience of using the thing.

**Comment by andres-asm** [comment]
Ahh yeah dolphin bar, no I was thinking for dolphin's USB passthrough
feature.
There are ways to use real wiimotes in dolphin without passthrough too, but
I still think that would be some sort of passthrough from RetroArch's
perspective.

**Comment by hiddenasbestos** [comment]
Is it working for you now @retro-wertz  ?
